# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-09 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0002_auto_20240709_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
